"""Adding referal code fields

Revision ID: 4351987f8334
Revises: 
Create Date: 2025-07-21 05:34:09.909748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4351987f8334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reffered_code', sa.String(length=20), nullable=True))
    op.alter_column('users', 'referral_code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               type_=sa.String(length=6),
               existing_nullable=True)
    op.create_index(op.f('ix_users_reffered_code'), 'users', ['reffered_code'], unique=False)
    op.drop_column('users', 'referred_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referred_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=20), nullable=True))
    op.drop_index(op.f('ix_users_reffered_code'), table_name='users')
    op.alter_column('users', 'referral_code',
               existing_type=sa.String(length=6),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               existing_nullable=True)
    op.drop_column('users', 'reffered_code')
    # ### end Alembic commands ###
