"""Adding referal code fields

Revision ID: dca316c470dd
Revises: 
Create Date: 2025-07-21 05:00:34.588238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca316c470dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(length=6), nullable=True))
    op.drop_index(op.f('ix_users_reffered_code'), table_name='users')
    op.create_index(op.f('ix_users_reffered_code'), 'users', ['reffered_code'], unique=False)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_reffered_code'), table_name='users')
    op.create_index(op.f('ix_users_reffered_code'), 'users', ['reffered_code'], unique=True)
    op.drop_column('users', 'referral_code')
    # ### end Alembic commands ###
